### ISSUE TITLE
Returning HTML rather than stripped text

### ISSUE THREAD

**Issue by ux-leap** [haochi/jquery.googleSuggest#3]
Hi hoachi

Could you suggest how to return actual google html to the dropdown rather than stripped text? Google returns `car<b>max</b>` and the highlight matches google search.

Thanks

**Comment by haochi** [comment]
Just change [this line](https://github.com/haochi/jquery.googleSuggest/blob/d2c789bb7ac8aa1f9437150466610743999f857e/jquery.googleSuggest.js#L31) to `return item[0];`

**Comment by ux-leap** [comment]
Hi I tried that before but jquery UI returns actual HTML rather than formated text, also the text which is going to the final input should be clean so you can hit enter and search for it. Check out here [https://jsbin.com/yadeyivozo/edit?html,output](url) Thanks

**Comment by haochi** [comment]
Okay looks like you need to use an extension for that.

> Independent of the variant you use, the label is always treated as text. If you want the label to be treated as html you can use Scott González' html extension.

http://api.jqueryui.com/autocomplete/#option-source
